Contact Me Section
Fene-87/Portfolio pull request #3
Opened 2022-12-06 22:10 UTC by Fene-87

I include a contact me section which contains a form

2022-12-06 22:16 UTC, Debas-31 reviewed
Hi @Fene-87 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:  :negative_squared_cross_mark:  :negative_squared_cross_mark: 

- [ ] You have submitted a project PR without pair programming, and your partner has not contributed a piece of code to your PR. Please ask your partner to contribute to your repo, and then you also contribute to his/her repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-07 14:55 UTC, Fene-87 commented
Pair programming partner added button to my form

2022-12-07 15:22 UTC, christianbiring1 requested changes
Hi @Fene-87 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/206218794-f6f9b530-e03f-4b06-bc06-efd24befee38.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 15:22 UTC, christianbiring1 commented on index.html
> +    <footer class="contact">
- [ ] Kindly make sure you use some semantic tag on your page for the better your HTML is structured the better SEO your page will be. The `footer` tag doesn't have any semantic meaning here. 
`hint: You may consider using a section or a generic div`
You can check [here](https://www.w3schools.com/tags/tag_footer.asp) when to use a section tag

2022-12-07 15:22 UTC, christianbiring1 commented on index.html
> +                hestiate to contact me.
[OPTIONAL]
- [ ] You may also consider giving the about Me section of your page a width of `100%` because it's supposed to fit the width of the screen size.
![Screenshot from 2022-12-07 17-16-13](https://user-images.githubusercontent.com/97100091/206218297-ef49baf1-b5bc-4bd0-af9b-0c64cf2c4bac.png)

2022-12-07 16:34 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @Fene-87 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 17:09 UTC, merged